version: "3.8"
services:
  web:
    build: ./app
    image: 533917248548.dkr.ecr.us-east-1.amazonaws.com/workshop2-1:workshop2_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres
      - DB_PASSWORD=<PASSWORDHERE>
      - DB_HOST=<HOSTNAME HERE>
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=<HOSTHERE>
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: <IMAGEINFOHERE>
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:
